import exceptions
import fib

print(fib(5))
